version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portaldesa-app
    container_name: portaldesa-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=DESA-LARAVEL
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    ports:
      - "9000:9000"

  webserver:
    image: nginx:alpine
    container_name: portaldesa-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: portaldesa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: DESA-LARAVEL
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: portaldesa-cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiNjE1NzhkZDhiMzMxNzYyMzNlNGM3ZjI5MDYwMmJmMzUiLCJ0IjoiNjJjZTA2YzItNzM5ZC00ZjQ4LThkZWUtOWM1ZDI2YWQ4ZDA5IiwicyI6Ik5qYzVNalZqTmpFdE56VmpNQzAwWW1OaUxUaGtZVEV0WTJZNFl6WmpObU5sWlRobCJ9 --url http://webserver:80
    restart: unless-stopped
    depends_on:
      - webserver

volumes:
  dbdata:
